# Generated by Django 2.1 on 2018-08-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=100)),
                ('repos_url', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
    ]
