# Generated by Django 2.1 on 2018-08-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_userpublicrepodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpublicrepodata',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
